# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
    ]
