# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=30)),
                ('street_number', models.PositiveIntegerField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=6)),
                ('building_number', models.PositiveIntegerField(blank=True)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(choices=[(1, 'POLAND'), (2, 'USA'), (3, 'GERMANY'), (4, 'FRANCE')], default='POLAND', max_length=9)),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
    ]
