# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Event', '0002_auto_20160823_2148'),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(blank=True)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecondaryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(blank=True)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile')),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comment.PrimaryComment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='primarycomment',
            name='answers',
            field=models.ManyToManyField(to='Comment.SecondaryComment'),
        ),
        migrations.AddField(
            model_name='primarycomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile'),
        ),
        migrations.AddField(
            model_name='primarycomment',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.Event'),
        ),
    ]
