# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0002_auto_20160823_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarycomment',
            name='answers',
            field=models.ManyToManyField(blank=True, to='Comment.SecondaryComment'),
        ),
        migrations.AlterField(
            model_name='secondarycomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Comment.PrimaryComment'),
        ),
    ]
