# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True, unique=True)),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('spots', models.PositiveIntegerField(null=True)),
                ('cur_capacity', models.PositiveIntegerField(default=0, editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.Category')),
            ],
        ),
    ]
