# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_end',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_start',
            new_name='date_start',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='spots',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='person_limit',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
